## BASIC TENSOR FLOW

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

## Constructing tensors from numpy array and lists

In [2]:
np.set_printoptions(precision=3)
a = np.array([1, 2, 3], dtype=np.int32)
b = [1, 2, 3, 4, 5]
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [3]:
t_zeros = tf.zeros((2, 4, 5))

In [4]:
t_zeros

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [5]:
t_random = tf.random.uniform((2, 3, 4))

In [9]:
t_random

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1.897e-01, 5.991e-01, 1.382e-01, 6.939e-01],
        [3.709e-01, 7.902e-01, 7.171e-01, 8.801e-01],
        [3.725e-01, 9.351e-01, 8.537e-01, 9.862e-01]],

       [[2.276e-02, 4.783e-01, 2.968e-01, 6.178e-02],
        [1.629e-01, 5.424e-03, 7.951e-01, 9.140e-04],
        [8.134e-01, 4.279e-01, 5.277e-01, 5.395e-01]]], dtype=float32)>

## Transpose reverses the order of indices of a tensor

In [10]:
t_transpose = tf.transpose(t_random)

In [11]:
t_transpose

<tf.Tensor: shape=(4, 3, 2), dtype=float32, numpy=
array([[[1.897e-01, 2.276e-02],
        [3.709e-01, 1.629e-01],
        [3.725e-01, 8.134e-01]],

       [[5.991e-01, 4.783e-01],
        [7.902e-01, 5.424e-03],
        [9.351e-01, 4.279e-01]],

       [[1.382e-01, 2.968e-01],
        [7.171e-01, 7.951e-01],
        [8.537e-01, 5.277e-01]],

       [[6.939e-01, 6.178e-02],
        [8.801e-01, 9.140e-04],
        [9.862e-01, 5.395e-01]]], dtype=float32)>

## squeeze reduces rank of the tensor

In [12]:
t_squeeze = tf.squeeze(t_random)

In [13]:
t_squeeze.shape

TensorShape([2, 3, 4])

## tensor multiply is point wise multiplication of two tensors

In [33]:
t1 = tf.random.uniform((5, 3))
t2 = tf.random.uniform((5, 3))

In [34]:
t3 = tf.multiply(t1, t2)

In [35]:
t1

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.913, 0.052, 0.361],
       [0.801, 0.815, 0.168],
       [0.53 , 0.617, 0.458],
       [0.791, 0.288, 0.946],
       [0.025, 0.136, 0.56 ]], dtype=float32)>

In [36]:
t2

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.516, 0.582, 0.6  ],
       [0.782, 0.695, 0.29 ],
       [0.974, 0.716, 0.922],
       [0.96 , 0.166, 0.341],
       [0.94 , 0.818, 0.981]], dtype=float32)>

In [37]:
t3

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.471, 0.03 , 0.217],
       [0.627, 0.566, 0.049],
       [0.516, 0.441, 0.422],
       [0.759, 0.048, 0.322],
       [0.024, 0.111, 0.55 ]], dtype=float32)>

## Reduces the tensor along a rank direction

In [19]:
t1 = tf.math.reduce_mean(t1, axis=0)

In [20]:
t2 = tf.math.reduce_std(t2, axis=1)

In [21]:
t3 = tf.math.reduce_sum(t2, axis=0)

In [22]:
t1

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.613, 0.543, 0.443], dtype=float32)>

In [28]:
t2 = tf.reshape(t2, (1, 5)) 

In [24]:
t3

<tf.Tensor: shape=(), dtype=float32, numpy=1.4290156>

## Matrix multiplication of tensor

- Same as contraction operation of higher rank tensors

In [38]:
t7 = tf.linalg.matmul(t1, t2, transpose_b=True)

In [39]:
t8 = tf.linalg.matmul(t1, t2, transpose_a=True)

## Spliting the tensor in different sizes

In [40]:
t = tf.random.uniform((6,))
t1 = tf.split(t, num_or_size_splits=3)
t2 = tf.split(t, num_or_size_splits=[3, 2, 1])


# Constructing DataSet From Tensor

In [41]:
a = [1.2, 3.4, 7.5, 4.1, 5.0, 1.0]

ds = tf.data.Dataset.from_tensor_slices(a)

for ele in ds:
    print(ele.numpy())

1.2
3.4
7.5
4.1
5.0
1.0


In [42]:
ds_split = ds.batch(3)

In [43]:
ds_split

<BatchDataset shapes: (None,), types: tf.float32>

In [44]:
for ele in ds_split:
    print(ele.numpy())

[1.2 3.4 7.5]
[4.1 5.  1. ]


In [45]:
tf.random.set_seed(1)

In [46]:
t_x = tf.random.uniform((4, 3))

In [47]:
t_y = tf.range(4)

In [48]:
t_x

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.165, 0.901, 0.631],
       [0.435, 0.292, 0.643],
       [0.976, 0.435, 0.66 ],
       [0.605, 0.637, 0.614]], dtype=float32)>

In [49]:
ds_x = tf.data.Dataset.from_tensor_slices(t_x)
ds_y = tf.data.Dataset.from_tensor_slices(t_y)

In [50]:
ds_joint = tf.data.Dataset.zip((ds_x, ds_y))

In [51]:
ds_joint

<ZipDataset shapes: ((3,), ()), types: (tf.float32, tf.int32)>

In [52]:
for ele in ds_joint:
    print(ele[0].numpy())
    print(ele[1].numpy())

[0.165 0.901 0.631]
0
[0.435 0.292 0.643]
1
[0.976 0.435 0.66 ]
2
[0.605 0.637 0.614]
3


In [53]:
ds_trans = ds_joint.map(lambda x, y: (x*2 - 1, y))

In [54]:
for ele in ds_trans:
    print(ele[0].numpy())

[-0.67   0.803  0.262]
[-0.131 -0.416  0.285]
[ 0.952 -0.13   0.32 ]
[0.21  0.273 0.229]


## EXAMPLE USING CAT and DOG IMAGES

In [55]:
pip install os

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os


In [63]:
import os
import pathlib

imdir_path = pathlib.Path('cat_dog_images')
file_list = [str(path) for path in imdir_path.glob('*.jpg')]


In [ ]:
fig = plt.figure(figsize=(10, 5))


for i, file in enumerate(file_list):
    
    img_raw = tf.io.read_file(file)
    img = tf.image.decode_image(img_raw)
    
    print('Image shape: ', img.shape)
    ax = fig.add_subplot(2, 3, i+1)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.imshow(img)
    ax.set_title(os.path.basename(file), size=15)
    
plt.tight_layout()
plt.show()

In [65]:
pip install keras